"""Central project state — the project.json document.

Every pipeline stage reads and updates this. A Scene carries everything the
later stages need: narration text, an image prompt, and produced asset paths.

The document is persisted through `storage` (filesystem by default, PostgreSQL
when DATABASE_URL is set); the project's media assets always live on disk
under projects/<slug>/ regardless of backend.
"""

from __future__ import annotations

import shutil
from dataclasses import asdict, dataclass, field, fields
from pathlib import Path

from . import storage
from .config import DATA_DIR

PROJECTS_DIR = DATA_DIR / "projects"


@dataclass
class Scene:
    id: int
    text: str                      # narration / voiceover for this scene
    image_prompt: str = ""         # prompt for the image generator
    est_duration_sec: float = 0.0  # estimated narration length
    audio_path: str = ""           # filled by the tts stage
    image_path: str = ""           # filled by the images stage
    # Provenance for the image (search path) — needed to credit/publish legally.
    image_source: str = ""         # e.g. "openverse", "pexels"
    image_license: str = ""        # license short name, e.g. "CC BY 2.0"
    image_attribution: str = ""    # creator / photographer
    image_credit_url: str = ""     # page to link back to
    # --- production blueprint (the director team fills these; the user edits
    #     them in the dashboard; each module "decodes" its part) ---------------
    visual_type: str = "search"    # how to make the image: search|generate|chart|animation
    voice: str = ""                # per-scene voice id/name (else the project voice)
    delivery: str = ""             # voiceover delivery note: emotion, pace, emphasis
    sfx: list[dict] = field(default_factory=list)  # [{"cue": str, "at_sec": float}]
    music: str = ""                # music mood/cue for this beat (else project bed)
    transition: str = ""           # transition INTO this scene: cut|fade|slide|...
    animation: str = ""            # motion hint: kenburns-in|kenburns-out|pan-left|...
    notes: str = ""                # director/showrunner notes for this scene


@dataclass
class Project:
    slug: str
    title: str = ""
    aspect: str = "16:9"           # "16:9" | "9:16"
    script_raw: str = ""
    script_human: str = ""
    scenes: list[Scene] = field(default_factory=list)
    video_path: str = ""           # filled by the montage stage
    thumbnail_path: str = ""        # the SELECTED thumbnail (one of thumbnails)
    thumbnails: list[str] = field(default_factory=list)  # all generated variants
    captions: dict = field(default_factory=dict)  # {srt, vtt, burned} from the captions stage
    # --- production blueprint (project level; set by the director team) -------
    channel: str = ""              # the Channel slug this video belongs to
    status: str = "draft"          # workflow stage: draft | ready | published
    theme: str = ""                # the niche/theme this belongs to (content memory)
    voice: str = ""                # default voiceover voice for the whole video
    music: str = ""                # global music-bed mood
    style: str = ""                # visual style guide applied across scenes
    blueprint_notes: str = ""      # showrunner's overall production notes
    source_idea: dict = field(default_factory=dict)  # the Idea this came from
    # Everything needed to POST the video to YouTube — generated by the publish
    # stage: {titles[], description, tags[], hashtags[], chapters[{time,label}],
    # pinned_comment, category}. Editable in the dashboard before publishing.
    publish: dict = field(default_factory=dict)

    # --- persistence ---------------------------------------------------------
    @property
    def dir(self) -> Path:
        return PROJECTS_DIR / self.slug

    @property
    def json_path(self) -> Path:
        return self.dir / "project.json"

    def save(self) -> Path:
        self.dir.mkdir(parents=True, exist_ok=True)  # asset dir (audio/images/output)
        storage.store().put("project", self.slug, asdict(self))
        return self.json_path

    @classmethod
    def from_dict(cls, data: dict) -> "Project":
        # Tolerate older/newer documents: drop keys the dataclasses don't know.
        data = dict(data)
        sf = {f.name for f in fields(Scene)}
        scenes = [Scene(**{k: v for k, v in s.items() if k in sf})
                  for s in data.pop("scenes", [])]
        pf = {f.name for f in fields(cls)}
        return cls(scenes=scenes, **{k: v for k, v in data.items() if k in pf})

    @classmethod
    def load(cls, slug: str) -> "Project":
        data = storage.store().get("project", slug)
        if data is None:
            raise FileNotFoundError(f"no project '{slug}'")
        return cls.from_dict(data)

    @classmethod
    def exists(cls, slug: str) -> bool:
        return storage.store().exists("project", slug)

    @classmethod
    def list(cls) -> list["Project"]:
        out = []
        for data in storage.store().all("project"):
            try:
                out.append(cls.from_dict(data))
            except Exception:  # noqa: BLE001 — skip an unreadable project
                continue
        return out

    @classmethod
    def delete(cls, slug: str) -> None:
        """Remove the document AND the project's asset directory."""
        storage.store().delete("project", slug)
        shutil.rmtree(PROJECTS_DIR / slug, ignore_errors=True)

    # --- scene editing -------------------------------------------------------
    # scene.id is a STABLE unique key (it names the asset files, e.g.
    # audio/scene_03.mp3); list order is the playback order. So reordering and
    # deleting never renumber — assets stay valid and ids never collide.
    def scene_by_id(self, sid: int) -> "Scene | None":
        return next((s for s in self.scenes if s.id == sid), None)

    def next_scene_id(self) -> int:
        return (max((s.id for s in self.scenes), default=0)) + 1


def invalidate_stale_assets(project: "Project", scene: "Scene", changed: set) -> list[str]:
    """When a scene's SOURCE fields change, drop only that scene's now-stale rendered
    assets so the next (idempotent) run regenerates just this scene and leaves the rest
    untouched. text -> voice is stale; image_prompt / visual_type -> image is stale.
    Returns a list of what was cleared (for logging)."""
    cleared: list[str] = []
    if (changed & {"text", "voice"}) and scene.audio_path:   # narration or cast voice changed
        f = project.dir / scene.audio_path
        if f.exists():
            try:
                f.unlink()
            except OSError:
                pass
        scene.audio_path = ""
        cleared.append("voice")
    if (changed & {"image_prompt", "visual_type"}) and scene.image_path:
        f = project.dir / scene.image_path
        if f.exists():
            try:
                f.unlink()
            except OSError:
                pass
        scene.image_path = ""
        cleared.append("visual")
    return cleared
